package com.nsbm.uni_cricket_360.enums;

public enum BowlingStyle {
    RIGHT_ARM_MEDIUM, RIGHT_ARM_FAST, RIGHT_ARM_OFF_BREAK, RIGHT_ARM_LEG_BREAK,
    LEFT_ARM_MEDIUM, LEFT_ARM_FAST, LEFT_ARM_ORTHODOX, LEFT_ARM_CHINAMAN
}
